-- ==========================================================================
-- HARNESS // Executive OS - Supabase PostgreSQL Schema
-- Realtime Synchronization Engine for iOS & Desktop
-- ==========================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Tasks Table (Daily Tasks & Checklists)
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    category text default 'General',
    is_tum boolean default false,
    completed boolean default false,
    date text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Daily Logs Table (Schedule Blocks, Exercises, Scratchpad)
create table if not exists public.daily_logs (
    date text primary key,
    wake_time text,
    sleep_time text,
    scratchpad text default '',
    reflection_worked text default '',
    reflection_slipped text default '',
    reflection_tomorrow text default '',
    completed_blocks text default '',
    completed_exercises text default '',
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Metro Stations Table (TUM Roadmap & Deliverables)
create table if not exists public.metro_stations (
    id text primary key,
    name text not null,
    phase text not null,
    month_label text not null,
    year_month text not null,
    is_major boolean default false,
    status text default 'upcoming',
    objective text,
    deliverables jsonb default '{}'::jsonb,
    completed_deliverables jsonb default '[]'::jsonb,
    order_idx integer not null
);

-- 4. Body Metrics Table (Weigh-ins, Nutrition)
create table if not exists public.body_metrics (
    id bigint generated by default as identity primary key,
    date text not null,
    weight_kg numeric(5,2) not null,
    calories_met boolean default false,
    protein_met boolean default false,
    notes text default '',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Workouts Table (Gym, Boxing, Running)
create table if not exists public.workouts (
    id bigint generated by default as identity primary key,
    date text not null,
    workout_type text not null,
    details text default '',
    intensity integer default 7,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Projects Table (Active Sprints & Next Actions)
create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text default '',
    local_path text default '',
    github_url text default '',
    current_milestone text default '',
    next_action text default '',
    deadline text default '',
    notes text default '',
    status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime for all tables
alter publication supabase_realtime add table public.tasks;
alter publication supabase_realtime add table public.daily_logs;
alter publication supabase_realtime add table public.metro_stations;
alter publication supabase_realtime add table public.body_metrics;
alter publication supabase_realtime add table public.workouts;
alter publication supabase_realtime add table public.projects;

-- Enable Row Level Security (Open for single user / personal token)
alter table public.tasks enable row level security;
alter table public.daily_logs enable row level security;
alter table public.metro_stations enable row level security;
alter table public.body_metrics enable row level security;
alter table public.workouts enable row level security;
alter table public.projects enable row level security;

-- Create open policies for personal app access
create policy "Allow all access to tasks" on public.tasks for all using (true) with check (true);
create policy "Allow all access to daily_logs" on public.daily_logs for all using (true) with check (true);
create policy "Allow all access to metro_stations" on public.metro_stations for all using (true) with check (true);
create policy "Allow all access to body_metrics" on public.body_metrics for all using (true) with check (true);
create policy "Allow all access to workouts" on public.workouts for all using (true) with check (true);
create policy "Allow all access to projects" on public.projects for all using (true) with check (true);
